start_date: 2020-06-22
end_date: 2020-06-29
data_dir: "/lustre/or-hydra/cades-birthright/nickrobison/mobility-analysis/data"
cbg_shp: "reference/census/block_groups.shp"
county_shp: "reference/census/tl_2019_us_county.shp"
poi_parquet: "reference/Joined_POI.parquet"
patterns_csv: "safegraph/weekly-patterns/"
output_dir: "output"
output_name: "epi_rank"
log_dir: "logs"